// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAecgjpBDY3dylIuHpRSk1toHF2GcXWXqo',
    appId: '1:205912567318:web:4916770acb0f41b7af4f37',
    messagingSenderId: '205912567318',
    projectId: 'instagram-clone-flutikx',
    authDomain: 'instagram-clone-flutikx.firebaseapp.com',
    storageBucket: 'instagram-clone-flutikx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5F75v7IlORahln7P21ijt6m_pBg56N-o',
    appId: '1:205912567318:android:25370e79230d18eeaf4f37',
    messagingSenderId: '205912567318',
    projectId: 'instagram-clone-flutikx',
    storageBucket: 'instagram-clone-flutikx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBoyoKccKHAKdHO8EZjjgfuaBzaDs-SYA',
    appId: '1:205912567318:ios:0a2f47c5c126ab1baf4f37',
    messagingSenderId: '205912567318',
    projectId: 'instagram-clone-flutikx',
    storageBucket: 'instagram-clone-flutikx.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
